### PR TITLE
Fix missing attributes Alternative Text

### PR DESCRIPTION
**Pull request by skinkie**

### CODE REVIEW

**Review by ue71603 — APPROVED** [review]

**Comment by Aurige** [comment]
What is the difference between the **lang** we already have and the **useForLanguage** that is added here ?

image

I would see this PR as en enhancement more than a bug (and therefore target Next)

**Comment by skinkie** [comment]
> What is the difference between the **lang** we already have and the **useForLanguage** that is added here ?

No clue, that attribute is used in the _restriction base_.

**Comment by Aurige** [comment]
Ok, sorry I missed your point .. I agree that this correction looks necessary to get the proper restriction... also it currently works without it (examples are using **order** and **useForLanguage** )

**Comment by skinkie** [comment]
> Ok, sorry I missed your point .. I agree that this correction looks necessary to get the proper restriction... also it currently works without it (examples are using **order** and **useForLanguage** )

That is an upstream bug.

**Comment by skinkie** [comment]
Can be closed, not a bug.

**Pull request closed without merging**
