### PR TITLE
Enhancement tmcr deck plan seating plan

### PR DESCRIPTION
**Pull request by nick-knowles**
Deck plan and Seating plan enhancements

### CODE REVIEW

**Comment by ue71603** [comment]
@Aurige ready for review?

**Comment by Aurige** [comment]
> @Aurige ready for review?

@nick-knowles said that he wanted/needed to update all deck plan related PRs

**Comment by ue71603** [comment]
done in #615

**Comment by trurlurl** [comment]
Removing "needs documentation update" label since closed without having been merged.

**Pull request closed without merging**
