### PR TITLE
EPIAP: PlatformHeight introduced on StopPlaceSpace

### PR DESCRIPTION
**Pull request by skinkie**

### CODE REVIEW

**Comment by Aurige** [comment]
Shouldn't it be on Quays ? StopPlaceSpace can be waiting rooms, corridors, etc. I since it is an enhancement it should go to "next"

**Comment by skinkie** [comment]
@Aurige we already had this discussion. We want to have in Quays, BoardingPositions, etc. If there should be introduced a different substitiongroup to facilitate enhancements that only relate to things along side of the track, that should be modelled first upstream.

**Comment by Aurige** [comment]
Yes I understood that this information needs to be shared between Quays and BoardingPositions, but that's not a reason to spread it to other unrelated object. I would recommend doing an XSD Group , as it is most usually done in NeTEx, and use that group in both objects. Another to go could be to detail the restriction on AccessSpace and VehicleStoppingPlace, but that looks a bit unnatural too me.

**Comment by ue71603** [comment]
May I ask you @skinkie  and @Aurige to resolve this? If modeling in a group occurs, who does it?

**Comment by ue71603** [comment]
Is replaced by: https://github.com/NeTEx-CEN/NeTEx/pull/298

**Pull request closed without merging**
