### PR TITLE
Creection_Bug_AccessEquipment

### PR DESCRIPTION
**Pull request by ue71603**
Christophe: It took me forever to understand what as happening with placeEquipments. I finally solved the issue this way
	
	<xsd:simpleType name="AccessEquipmentIdType">
		<xsd:annotation>
			<xsd:documentation>Type for identifier of an ACCESS EQUIPMENT.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="InstalledEquipmentIdType"/>
	</xsd:simpleType>

	<xsd:element name="AccessEquipmentRef" type="AccessEquipmentRefStructure" abstract="true" substitutionGroup="InstalledEquipmentRef">
		<xsd:annotation>
			<xsd:documentation>Identifier of an ACCESS EQUIPMENT.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="AccessEquipmentRefStructure">
		<xsd:annotation>
			<xsd:documentation>Type for a reference to an ACCESS EQUIPMENT.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>

			<xsd:restriction base="InstalledEquipmentRefStructure">
				<xsd:attribute name="ref" type="AccessEquipmentIdType" use="required">
					<xsd:annotation>
						<xsd:documentation>Identifier of an ACCESS EQUIPMENT.</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>

It solves the issue.... but this may have some side effect also, can you check how it looks on your side ? We also may need to check if there are other similar issues.
If that's Ok, it can be PRed

### CODE REVIEW

**Review by Aurige — APPROVED** [review]

**Comment by ue71603** [comment]
The relevant part of the change was commented out. Now it works... Also added a lot of things from chapter 7 EPIAP so that it is in an example.

**Comment by ue71603** [comment]
@skinkie  @duexw : review?

**Comment by Aurige** [comment]
long work, little gain with risks of mistakes ... not really tempted on my side ;-)

**Comment by skinkie** [comment]
> long work, little gain with risks of mistakes ... not really tempted on my side ;-)

The code generation would really benefit from it. (the remove sequences part)

**Comment by ue71603** [comment]
...and it is necessary for EPIAP....

**Review by skinkie — APPROVED** [review]

**Pull request merged**
