### PR TITLE
remove description in PathLinkInSequenceGroup

### PR DESCRIPTION
**Pull request by ue71603**
would be duplicated otherwise

### CODE REVIEW

**Comment by ue71603** [comment]
@skinkie for this not possible as description was used. close?

**Comment by skinkie** [comment]
> @skinkie for this not possible as description was used. close?

What you mean in this case with 'used'? Are there two descriptions used at the same place?

**Comment by ue71603** [comment]
Hi Stefan
Removing it in master resultated in many invalid examples (see ci /run). So there is no other one (or at least it is not at exactly the same place).

**Comment by ue71603** [comment]
The problem is, that the Description now would need to be before the PathLinkRef

it was

* Description
* PathLinkRef
* Description

So the position of the Description would need to be changed in all examples.

image

**Comment by skinkie** [comment]
The suggestion was to remove it from _next_.

**Comment by ue71603** [comment]
no, was not: you referenced master in https://github.com/NeTEx-CEN/NeTEx/issues/748

**Comment by skinkie** [comment]
I am happy to update all the examples. But I wonder who uncarefully duplicated, provided the wrong examples (and caused this mess).

**Comment by skinkie** [comment]
> no, was not: you referenced master in #748

_In Next the same would go for PathLinkInSequenceGroup, removing the extra Description resolves the issue._

**Comment by ue71603** [comment]
I move the PR to next and update the examples.

**Pull request closed without merging**
