### PR TITLE
Feature/stop places

### PR DESCRIPTION
**Pull request by DWillDB**

### CODE REVIEW

**Comment by Aurige** [comment]
Can you elaborate about these example ? I see mentions of TSI-PRM, but there are no accessibility information. Also what is the_.adoc_ file for ?

**Comment by skinkie** [comment]
I would also argue that StopPlace cannot be used as root element.

**Comment by DWillDB** [comment]
Hello @Aurige and hello @skinkie, 
thank you very much for the input. We are currently working on mapping TSI-PRM to station infrastructure elements. The current status is work in progress. There was a misunderstanding here; the pull request should have been made to a forked repository. Therefore, I will close this pull request and create it internally within our organization. If we have any further questions about NeTEx, can we contact you for assistance?

**Comment by Aurige** [comment]
> can we contact you for assistance?

sure :-)

**Pull request closed without merging**
