### PR TITLE
Delete netex_all_filters.xsd

### PR DESCRIPTION
**Pull request by ue71603**

### CODE REVIEW

**Comment by ue71603** [comment]
messed something up.

**Comment by ue71603** [comment]
should fix the second part of: https://github.com/NeTEx-CEN/NeTEx/issues/307

**Review by skinkie — APPROVED** [review]
Its empty... make it go away!

**Comment by ue71603** [comment]
I deleted a file. That's all.. :-)

**Comment by ue71603** [comment]
@Aurige  review?

**Review by Aurige — APPROVED** [review]

**Pull request closed without merging**
