### PR TITLE
Add 'provisional' to ServiceAlterationEnumeration

### PR DESCRIPTION
**Pull request by syversenkr**
For long term journey planning, relevant as a ServiceAlteration(Type) either before being 'planned' (finalized) or as an intermediary state before 'cancellation' or 'replaced'.

### CODE REVIEW

**Review by Aurige — APPROVED** [review]

**Comment by syversenkr** [comment]
@skinkie / @ue71603 / @Aurige 
Please merge PR when appropriate.

**Comment by syversenkr** [comment]
Description for 'provisional' is new.
_If native English speakers have input, please advice._
The other added descriptions are from table **ServiceAlteration – Allowed values** in NeTEx part 2

**Review by ue71603 — APPROVED** [review]

**Comment by nick-knowles** [comment]
This needs to have documentation comments added into XML as otherwise it is very confusing - it is not at all obvious what provisional is

**Provisional** - Provisional service that has not yet been firmly scheduled for timetable.
**Planned** - Planned service in scheduled timetable.
**ExtraJourney** - Additional Service that was not in scheduled timetable.
**Cancellation** - Service in planned timetable that that has been cancelled.
**Replaced** Planned service that has been replaced with another journey.v

UML updated
image

**Comment by ue71603** [comment]
comments from @nick-knowles  addressed in #626

**Pull request merged**
