### PR TITLE
New modes at# add short name to mobility service

### PR DESCRIPTION
**Pull request by nick-knowles**
As per review meeting 2021.04.14

### CODE REVIEW

**Comment by skinkie** [comment]
xsd/netex_framework/netex_utility/tmp0000.xsd

**Comment by Aurige** [comment]
@nick-knowles this PR contains both the shortName change and the previous  MobileApp one, I guess that's a branch issue 
@skinkie or @syversenkr : can you elaborate on how to create a PR on the top of another (Nick needs to have all the changes together, not a repo with several independent branches containing separated changes)

**Comment by skinkie** [comment]
@Aurige Nick needs to use the new modes as base branch. And create branches from that. If a branch is merged, he pulls the base branch again.

**Comment by Aurige** [comment]
Thanks @skinkie 
The question is how to work on a sequence of PR without needing to wait for the validation/merge of the previous ones, but still having them all in the project. That's the case her: we had a group meeting where we validated about 6 fixes to ease the GBFS mapping: we need to make them all together to get something consistent, but also PR them individually. What is the expected processes ?

**Comment by skinkie** [comment]
> Thanks @skinkie
> The question is how to work on a sequence of PR without needing to wait for the validation/merge of the previous ones, but still having them all in the project. That's the case her: we had a group meeting where we validated about 6 fixes to ease the GBFS mapping: we need to make them all together to get something consistent, but also PR them individually. What is the expected processes ?

Create a new branch, merge the branches you are interested in, continue the work?

**Comment by Aurige** [comment]
Yes, so you create a branch B1, commit+PR1, then create a branch B2 based on branch B1, commit+PR2 ... but then PR2 contains the commits from B1 and B2.... so it's not anymore unitary ! and you get overlaping PRs 
Am I missing something ?

**Comment by skinkie** [comment]
You can still merge B1, B2 in that sequence.

**Comment by Aurige** [comment]
Ok, if that's fine for you that's fine for me (I will add this to the doc you started)
@nick-knowles  is this Ok for you ?

**Comment by skinkie** [comment]
@Aurige it does have the implication that if there are changes requested for B1, B2 should be rebased.

**Comment by Aurige** [comment]
is the "**_git rebase upstream/new-modes B2_**" the proper one to use for this ?

**Comment by skinkie** [comment]
> is the "**_git rebase upstream/new-modes B2_**" the proper one to use for this ?

I was thinking more in the direction of B1, but after it has been merged, that would make sense.

**Pull request merged**
