### PR TITLE
Issue #143 Wrong type for BoardingHeight and GapToPlatform i

### PR DESCRIPTION
**Pull request by nick-knowles**
in AccessVehicleEquipment

Corrrect to be LengthType

### CODE REVIEW

**Comment by skinkie** [comment]
Contains changes that are unrelated to the description.

**Review by syversenkr — DISMISSED** [review]
Should also include type change in line 236 name="GapToPlatform" type="LengthType"

**Comment by Aurige** [comment]
Yes, and the issue is still in _netex_equipmentVehiclePassenger_version_ even in the new mode branch
@syversenkr can you do the proper PR ?

**Comment by syversenkr** [comment]
This PR should have addressed the new-modes branch, not master
Although most of this was already merged into the new-modes branch (in addition to lots of other ReadMe updates)

Have updated the new-modes to ensure all appropriate fixes are on this branch (https://github.com/NeTEx-CEN/NeTEx/commit/c212c42ed7b5fb1d34e992d241a90582e728a8e1), and recommend leaving this as is on master until new-modes is merged into master.

If agreement, this PR can be closed and the local "FIX-Issue143-GapToPlatform" branch deprecated.

**Review by skinkie — APPROVED** [review]

**Review by ue71603 — APPROVED** [review]

**Review by ue71603 — APPROVED** [review]

**Review by ue71603 — APPROVED** [review]

**Pull request merged**
