### PR TITLE
Removing double description in HeadwayJourneyGroupGroup

### PR DESCRIPTION
**Pull request by ue71603**
https://github.com/NeTEx-CEN/NeTEx/issues/748

### CODE REVIEW

**Comment by ue71603** [comment]
@Aurige  didn't break examples => removing is possible

**Review by skinkie — APPROVED** [review]

**Review by trurlurl — APPROVED** [review]

**Comment by Aurige** [comment]
No pb for next, but we need to ask the group for master ... (but that's Ok for me, personnaly)

**Comment by Aurige** [comment]
Ok to remove

**Comment by trurlurl** [comment]
This is in master, I'm not sure about the implications for the documentation. Is the same change also somewhere for next, or will this one be merged before V2.0?

**Comment by skinkie** [comment]
@trurlurl I'll sync next with master shortly.

**Pull request merged**
