### PR TITLE
Tap TSI examples

### PR DESCRIPTION
**Pull request by nick-knowles**
These are  as set of  examples of  encoding TAP TSI Data in NeTEx. No schema change.  They illustrate a number fo small issues taht need fixing.

### CODE REVIEW

**Review by Aurige — COMMENTED** [review]
[netex_nm_equipmentEnergy_version.xsd](https://github.com/NeTEx-CEN/NeTEx/pull/299/commits/af45a30cde2d381736aac1b06085e2562cdc3030#diff-2e3735f393ddc943c54f5c814f82d0b216459f40d9b6180cf9e328eddbde28f5) looks to be an old version (a cleaner one has already been merged)

**Comment by Aurige** [comment]
Thanks Nick for putting the work done with UIC back in NeTEx XML example
We have a small side effect here with the "**NewModes-Add type of battery chemistry**", from September 2021, we already have a merged version which that looks cleaner. Can you remove this file from the PR ?

**Review by ue71603 — CHANGES_REQUESTED** [review]
In a pull request about examples no XSD should be changed. But is already addressed by the comment from Christophe. Rest ok.

**Review by ue71603 — APPROVED** [review]

**Review by ue71603 — APPROVED** [review]

**Comment by ue71603** [comment]
OK...

**Pull request closed without merging**
