### PR TITLE
The remaining CR from Adrian's list

### PR DESCRIPTION
**Pull request by ue71603**
I think we will have to discuss it.

### CODE REVIEW

**Comment by ue71603** [comment]
I thought we discussed that I should add it there. Or should I do master?

**Comment by Aurige** [comment]
To me that's for 'Next' branch and requires a doc update

**Comment by ue71603** [comment]
Did it new with more things from Joost.

**Comment by trurlurl** [comment]
Removing "needs documentation update" label since closed without having been merged.

**Pull request closed without merging**
