### PR TITLE
fixed the (first problem with the current next branch ( support --> v…

### PR DESCRIPTION
**Pull request by ue71603**
…ersion)

As travis is not working, I am not sure, if it is all, but it fixes one.

### CODE REVIEW

**Comment by ue71603** [comment]
@skinkie  @Aurige  Please check this branch. Without this the next branch is not working!

**Comment by Aurige** [comment]
including _version.xsd insted of _support.xsd often triggers circular references .... what is the pb reported by Travis (XML Spy says it is Ok)

**Comment by skinkie** [comment]
xmllint does not report a problem, can we close this?

**Comment by ue71603** [comment]
fine with me.

**Pull request closed without merging**
