### PR TITLE
Retype all order elements to xsd:positiveInteger and fix the associated examples

### LINKED ISSUE #475: Investigate order attribute xsd:integer vs xsd:positiveInteger

### PR DESCRIPTION
**Pull request by skinkie**
This is a breaking change (with respect to the documentation) which mixes xsd:positiveInteger with xsd:integer.

The main difference is: positiveInteger starts at 1.

Please carefully consider the changes that have a mention on "Relative order". No examples exists with a negative relative order, but the design might allow them?

Fix #475

(apply after the required Id pull request)

### CODE REVIEW

**Review by trurlurl — APPROVED** [review]
Looks good to me.

**Comment by trurlurl** [comment]
@skinkie No, I cannot be sure about negative order numbers, I'm not sufficiently familiar with the structures in question.

**Comment by ue71603** [comment]
I think we moved the elevator order into an element. So it means that order is arbitrary.  And from N to Q everything can be ordered the same way ;-)

**Review by ue71603 — APPROVED** [review]

**Comment by skinkie** [comment]
Show me the breaking data.

**Comment by Aurige** [comment]
> Show me the breaking data.

The examples you had to correct ?

**Comment by skinkie** [comment]
> The examples you had to correct ?

The PassengerStopAssignment order should always have started at 1?

**Comment by Aurige** [comment]
Will be discussed in meeting #14 (October 4th)

**Comment by ue71603** [comment]
> Will be discussed in meeting #14 (October 4th)

Does this mean you are ok with it?

**Comment by Aurige** [comment]
> > Will be discussed in meeting #14 (October 4th)
> 
> Does this mean you are ok with it?

My mind is not fully made up about it (not against, but don't like its drawbacks)... and anyway whatever I prefer, we need the group validation to accept the drawbacks

**Comment by ue71603** [comment]
@Joostb61  RelativeLevelOrder is not affected. Only the order attributes are concerned.

**Comment by Aurige** [comment]
The group decision was : The PR is accepted but needs to be separated from the IdType fix on which it is stacked
_Note: may generate some backward compatibility issues_

**Comment by ue71603** [comment]
@skinkie  who will remove  the IdType part?  Should I rebase it?. Otherwise it was accepted by enough reviewers. Or do you want explicitly have acceptance by @Aurige

**Comment by skinkie** [comment]
If you only go for the changing or order element, I would cherry pick the specific commits.

**Comment by ue71603** [comment]
use the last four or so comments. and redo...

**Comment by Aurige** [comment]
How to express that order (mandatory) is not useful in some cases ? Make it non mandatory ? use value "1" for all orders ? 
Value 1 is the group's preferred choice ... to be described in the document (only when the order is meaningless)

**Comment by trurlurl** [comment]
Removing "documentation update needed" since closed without merging.

**Pull request closed without merging**
