### PR TITLE
Prioritize TAP TSI validation

### PR DESCRIPTION
**Pull request by skinkie**

### CODE REVIEW

**Comment by ue71603** [comment]
...I duplicated your work....

**Comment by skinkie** [comment]
> ...I duplicated your work....

Did you get paid for it?

**Comment by ue71603** [comment]
@Aurige  @skinkie   I updated everything exept two files
Netex_tap_trainhotel_1.xml and Netex_tap_tsi-B2-71-optimised.xml

The have a different problem
The assume there are:
-  validityParameterAssignments/GenericParameterAssignmentRef
- noticeAssignments/NoticeAssignmentRef
- FareStructureElement/accessRightParameterAssignments 
- other fare stuff

It seems to me that those reference something that doesn't exist.

Perhaps @nick-knowles  can have a go at it. But I think these two examples not to be reexamined.

**Review by EU-Agency-for-Railways — COMMENTED** [review]
Changes OK for File Netex_tap_tsi_B2-71-optimised.xml and Netex_tap_trainhotel_1.xml @nick-knowles could check the errors

**Comment by Aurige** [comment]
@nick-knowles to check why de 2 blocking files are not in the XML Spy project

**Review by ue71603 — APPROVED** [review]

**Comment by ue71603** [comment]
No answer from @nick-knowles . Files removed and ready to merge.

**Review by Aurige — APPROVED** [review]

**Review by trurlurl — APPROVED** [review]

**Pull request merged**
