### PR TITLE
PrivateCode für TimingPoint

### PR DESCRIPTION
**Pull request by ue71603**
Fixing https://github.com/NeTEx-CEN/NeTEx/issues/32

### CODE REVIEW

**Comment by skinkie** [comment]
My guess is that this fails because FarePoint is depending on TimingPoint and not the subsitution variant... but now you probably see why it would be benefitial to add it higher in the chain, but may break stuff. I would be interested how many of the examples would actually break.

**Comment by ue71603** [comment]
grmbl. worked fine for the tests I did with XMLSpy... back to the drawing board

**Comment by ue71603** [comment]
and jupp now the examples are breaking. @Aurige  Do you think that move could be done fpr next?

**Comment by JohanEntur** [comment]
ℹ️ https://github.com/NeTEx-CEN/NeTEx/pull/369

**Comment by trurlurl** [comment]
Removing "needs documentation update" label since closed without having been merged.

**Pull request closed without merging**
