### PR TITLE
Include DatedVehicleJourney and NormalDatedVehicleJourney to vehicleJourneys in TimetableFrame

### PR DESCRIPTION
**Pull request by syversenkr**
Specified in the standard and objects are defined in netex_datedVehicleJourney_version.xsd but currently unavailable as vehicleJourneys types in TimetableFrame due to XSD implementation error. 
Recommending these to be added per Basecamp/email exchange with @nick-knowles

### CODE REVIEW

**Comment by skinkie** [comment]
Do I understand this is another "lets nuke the repository with an ocean of changes that nobody could track back or review"-pull request ?

**Comment by syversenkr** [comment]
Please delete pull request!

**Comment by syversenkr** [comment]
I am unable to delete myself. Have tried to find the withdraw this PR since incorrect upstream due to the Entur not in sync.

These are old changes already included in CEN master looong back.

PS: I hate GIT

**Comment by syversenkr** [comment]
@skinkie Please delete the pull request completely, as it contains only clutter.

**Comment by skinkie** [comment]
Sadly not an option yet. https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

**Pull request closed without merging**
