### PR TITLE
Equipment place as site component

### PR DESCRIPTION
**Pull request by ue71603**
I am not sure, if we are good. That an EquipmentPlace can have an EquipmentPlace does not make me happy
image

### CODE REVIEW

**Comment by Aurige** [comment]
oups ! right, that's probably why it was initially a Place and not a SiteComponent .... it's raising other issues, and is not as straightforward as I anticipated :-( Let me think about it ...

**Comment by Aurige** [comment]
Since in Transmodel the SITE COMPONENT is just a king of wrapper inheriting from SITE ELEMENT, to avoid the previously  mentioned "circular reference" we can safely go with:

```
	<xsd:element name="EquipmentPlace" substitutionGroup="Place">
		<xsd:annotation>
			<xsd:documentation>Designated Place within a SITE for a locating EQUIPMENT.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:restriction base="EquipmentPlace_VersionStructure">
					<xsd:sequence>
						<xsd:sequence>
							<xsd:group ref="EntityInVersionGroup" minOccurs="0"/>
						</xsd:sequence>
						<xsd:sequence>
							<xsd:group ref="DataManagedObjectGroup"/>
						</xsd:sequence>
						<xsd:sequence>
							<xsd:group ref="GroupOfEntitiesGroup"/>
						</xsd:sequence>
						<xsd:sequence>
							<xsd:group ref="GroupOfPointsGroup"/>
						</xsd:sequence>
						<xsd:sequence>
							<xsd:group ref="ZoneGroup"/>
						</xsd:sequence>
						<xsd:group ref="PlaceGroup"/>
<!--CD PROPOSAL -->
						<xsd:sequence>
							<xsd:group ref="AddressablePlaceGroup"/>
						</xsd:sequence>
						<xsd:group ref="SiteElementGroup"/>
<!--       -->
						<xsd:sequence>
							<xsd:group ref="EquipmentPlaceGroup"/>
						</xsd:sequence>
					</xsd:sequence>
					<xsd:attribute name="id" type="EquipmentPlaceIdType">
						<xsd:annotation>
							<xsd:documentation>Identifier of  EQUIPMENT PLACE.</xsd:documentation>
						</xsd:annotation>
					</xsd:attribute>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="EquipmentPlace_VersionStructure">
		<xsd:annotation>
			<xsd:documentation>Type for an EQUIPMENT PLACE.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>

<!--			<xsd:extension base="Place_VersionStructure">                   CD PROPOSAL-->
			<xsd:extension base="SiteElement_VersionStructure"> <!--	CD PROPOSAL-->

				<xsd:sequence>
					<xsd:group ref="EquipmentPlaceGroup"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

```

**Comment by ue71603** [comment]
New update with Christophe's change. When ok, I will remove the comments.

**Review by Aurige — APPROVED** [review]

**Comment by ue71603** [comment]
Will work on the Travis problem tomorrow.

**Comment by skinkie** [comment]
@Aurige don't approve things that do not validate and still have comments in it.

**Comment by Aurige** [comment]
> @Aurige don't approve things that do not validate and still have comments in it.

Ok, sorry for that, I just wanted to validate the principle (but it of course have to validate ... it does on my local test, so that's most probably a minor issue)

**Comment by ue71603** [comment]
replayed by https://github.com/NeTEx-CEN/NeTEx/pull/277

**Pull request closed without merging**
