### PR TITLE
Update netex_servicePattern_support.xsd

### PR DESCRIPTION
**Pull request by ue71603**
Adding a possibility that the driver should be informed

### CODE REVIEW

**Comment by skinkie** [comment]
I don't want to sound "woke", but should that speaking part not be something more _general_?

**Comment by ue71603** [comment]
A suggestion?  speaktoStaffOnboard?

**Comment by skinkie** [comment]
I wondered if speaking is the right wording here. _Inform_ Driver also leaves room on the 'how'.

**Comment by Aurige** [comment]
If this is a request for a stop I would just extend the _RequestMethodType_ associated to _RequestStop_.
Currently we have 
```
<xsd:enumeration value="noneRequired">
	<xsd:annotation>
		<xsd:documentation>No action required to request stop</xsd:documentation>
	</xsd:annotation>
</xsd:enumeration>
<xsd:enumeration value="handSignal">
	<xsd:annotation>
		<xsd:documentation>Make hand signal to request stop</xsd:documentation>
	</xsd:annotation>
</xsd:enumeration>
<xsd:enumeration value="turnOnLight">
	<xsd:annotation>
		<xsd:documentation>Call number to request stop</xsd:documentation>
	</xsd:annotation>
</xsd:enumeration>
<xsd:enumeration value="stopButton">
	<xsd:annotation>
		<xsd:documentation>Press button at stop to request stop</xsd:documentation>
	</xsd:annotation>
</xsd:enumeration>
<xsd:enumeration value="phoneCall">
	<xsd:annotation>
		<xsd:documentation>Call number to request stop</xsd:documentation>
	</xsd:annotation>
</xsd:enumeration>
<xsd:enumeration value="mobileApp">
	<xsd:annotation>
		<xsd:documentation>Use mobile Application to request stop</xsd:documentation>
	</xsd:annotation>
</xsd:enumeration>
<xsd:enumeration value="sms">
	<xsd:annotation>
		<xsd:documentation>Use Sms to request stop</xsd:documentation>
	</xsd:annotation>
</xsd:enumeration>
<xsd:enumeration value="other">
	<xsd:annotation>
		<xsd:documentation>Use other method to request stop</xsd:documentation>
	</xsd:annotation>
</xsd:enumeration>
```
Also talking to drive is very unusual (and very often forbiden).

**Review by skinkie — APPROVED** [review]

**Pull request merged**
