### PR TITLE
Fix typo and doc of SharpsDisposal

### PR DESCRIPTION
**Pull request by frodrigo**

### CODE REVIEW

**Comment by skinkie** [comment]
Great catch!!

**Comment by frodrigo** [comment]
> I would support an XML example with this PR.

Not sure what you are asking for.

**Comment by skinkie** [comment]
You are updating the XSD due to a bug. But if we want to make sure that nobody is affected by such changes in the future, we should make an example using this element that is (automatically) validated prior to merging.

**Review by Aurige — APPROVED** [review]
some risks with backwarrd compatibility, but obviously a bug/typo to solve

**Comment by skinkie** [comment]
@Aurige the quicker they are resolved, the less impact ;)

**Review by skinkie — APPROVED** [review]

**Pull request merged**
