### PR TITLE
Documentation - Enhancement Readme

### PR DESCRIPTION
**Pull request by EliotTerrier**
**README format clarification:** 
- The changelog has been moved to the wiki and replaced by a version summary table. 
- Main directory functionalities reorganized for greater clarity.

**Readme added content:** 
- Main branches description table.

**Change in the repository:**
- Update of epip_common_profile.xml example.

@skinkie  @Aurige for your review

### CODE REVIEW

**Comment by skinkie** [comment]
The information contained in the README.md considering "the changelog" is not retained in any other file.
The extensive EPIP example is basically crippled, by removing the advanced ClassRelationShips.

**Comment by EliotTerrier** [comment]
> The information contained in the README.md considering "the changelog" is not retained in any other file. 

Thanks for the prompt feedback
 
Original change log included the detailed release notes for each version within the readme:
image

 
**Suggested change:**
- table with the version number, their date, short description and link toward the release notes
- link to the detailed version history on the suggested new wiki pages

Note: both detailed release notes and full version history are part of a [dedicated  section ](https://github.com/ITxPT/NeTEx/wiki/Release-history#release-history)in the suggested revamped wiki
image

**Comment by skinkie** [comment]
This pull request should not mix "the example" and "the readme" they are separate subjects.

**Comment by skinkie** [comment]
@EliotTerrier it does not work like this. This removes the file from the repository.

**Comment by EliotTerrier** [comment]
> This pull request should not mix "the example" and "the readme" they are separate subjects.

Indeed, sorry for my mistakes, can you close the PR? I'll make another one just for the README.

**Comment by skinkie** [comment]
I think this would be the quickest solution.

**Comment by EliotTerrier** [comment]
Many thanks for your support

**Comment by TuThoThai** [comment]
@skinkie, Thank you for your kind support and guidance.
@EliotTerrier will create a cleaner & new PR as soon as we close this one.

**Comment by skinkie** [comment]
@EliotTerrier regarding the example, why not a _new_ example instead of replacing it?

**Pull request closed without merging**
