### PR TITLE
Lets see how a downstream change works!

### PR DESCRIPTION
**Pull request by skinkie**

### CODE REVIEW

**Comment by skinkie** [comment]
@nick-knowles @Aurige you may press merge :)

**Comment by Aurige** [comment]
It looks Ok :-)

**Comment by Aurige** [comment]
Is it something we need to do manually for each update on Master (until New Modes is merged to master) or is there a kind of automation ?

**Comment by skinkie** [comment]
I don't know yet if it can be automated, but there is something under "Actions" that might allow it.

**Pull request merged**
