### PR TITLE
NewModes - Vehicle charging equipment

### PR DESCRIPTION
**Pull request by nick-knowles**
The VDV review comments put forward Vehicle charging elements. to manage the charging of electric vehicles.    Adding a charging  plan for vehicles needs further modelling so should be left to a future CR.  However it is straightforward to add a BatteryEquipment  and a ChargingEquipmentProfile based on the VDV values, and incorporating ISOstandard plug types.

### CODE REVIEW

**Comment by skinkie** [comment]
There you have it @nick-knowles.

First merge the new-modes branch in your VehicleChargingEquipment branch. Then commit the merge.

**Comment by Aurige** [comment]
> 
> 
> There you have it @nick-knowles.
> 
> First merge the new-modes branch in your VehicleChargingEquipment branch. Then commit the merge.

@skinkie I updated the README in PR VehicleChargingEquipment branch ... I think it should be Ok now, can you check ?

**Review by Aurige — APPROVED** [review]

**Comment by skinkie** [comment]
@Aurige  This branch is still conflicting...

**Comment by Aurige** [comment]
Conflicts should be solved now

**Pull request merged**
