### PR TITLE
Fix master

### PR DESCRIPTION
**Pull request by skinkie**
Travis does not seem to use the latest state, because the issues occur at the next validation.

Please approve, master broken.

### CODE REVIEW

**Review by ue71603 — APPROVED** [review]
so we already had those things in there from https://github.com/NeTEx-CEN/NeTEx/pull/57/files

**Comment by skinkie** [comment]
@ue71603 yes, that was the last thing I merged.

**Comment by ue71603** [comment]
my fault... sorry...did not check, if it was already in it.

**Review by Aurige — APPROVED** [review]

**Review by trurlurl — COMMENTED** [review]
Sorry for the delay...

**Pull request merged**
