### PR TITLE
Circle CI trigger config

### PR DESCRIPTION
**Pull request by syversenkr**
Generalized .circleci/config.yml in regard to hosting config, and additionally documented dependancies to Entur projects (open source)

### CODE REVIEW

**Comment by skinkie** [comment]
I hope @syversenkr knows what he is doing. I'll approve.

**Comment by Aurige** [comment]
> 
> 
> I hope @syversenkr knows what he is doing. I'll approve.

Same here ... can you elaborate what this enhancement is doing ?

**Comment by syversenkr** [comment]
The confic currently in the master branch was a inadvertent consequence of the previous (last spring) megamerge. 

Is really no point in having a Entur specific Circle CI config file in the CEN master repo. 

Have for this reason adjusted, to make it a generic template (currently non-functioning, must be adjusted to local setup) based on the previously included Entur Circle CI config.

This can either be used as a template, if Circle CI based build triggers is relevant at a future stage, if not useful the PR can be retracted, the branch deleted and the .circleci folder + config.yml be deleted from the CEN repo.

**Review by seime — CHANGES_REQUESTED** [review]
IMHO this repo is using a different build system, and there is no need for a CircleCI template as well. Should be removed from official repo (and only live inside Entur fork).

**Comment by Aurige** [comment]
> 
> 
> IMHO this repo is using a different build system, and there is no need for a CircleCI template as well. Should be removed from official repo (and only live inside Entur fork).

so we just need to drop _.circleci/config.yml_  from the repo ?

**Comment by seime** [comment]
> so we just need to drop _.circleci/config.yml_ from the repo ?

Yep

**Comment by skinkie** [comment]
@seime so don't merge this pull. And remove the file?

**Comment by syversenkr** [comment]
@skinkie Yes, delete pull and remove the CircleCI config file and folder

**Pull request closed without merging**
