### PR TITLE
Enhancement for Site - site levels etc

### PR DESCRIPTION
**Pull request by nick-knowles**
TM enhancement to support different level names in a SIte: Add SIteStructure, LevelInStructure
Also GroupOfSItes and GroupOfTariffZoness added to SIteFrame
Add uniqueness constraints for new elements.  Test case example provided

### CODE REVIEW

**Comment by skinkie** [comment]
@nick-knowles this way you work, reviewing and merging does not. Please only do a single change and always start from the current state of the branch you target.

**Comment by Aurige** [comment]
I'm a bit lost here ... I guess only the last commit is relevant (so it's best to have only this one in a dedicated branch for the PR: you should be able to create such a branch on top of the current state of 'next' and cherry pick the relevant commit to this new branch. From there you can create a new PR) 
This last commit adds a **_LevelInStructureRef_** but I can't find where it is used. Is there anything missing ?

**Comment by ue71603** [comment]
done in #615

**Comment by nick-knowles** [comment]
UML documentation

image

**Pull request closed without merging**
