### PR TITLE
enhancement-TMCR-add ACCEPTED DRIVER PERMITs

### PR DESCRIPTION
**Pull request by nick-knowles**
Add ACCEPTED DRIVER PERMITS to  SIMPLE VEHICLE TYpe

### CODE REVIEW

**Review by skinkie — CHANGES_REQUESTED** [review]
No, just no.

**Comment by Aurige** [comment]
@Nick the PR should be one (or a few lines) but you accidentally collect a lot of changes (mainly presentation/indentation) that create hundreds of small changes... so it is not easy to identify the real change, and there are a lot of unnecessary ones.

**Comment by nick-knowles** [comment]
When using XML spy I usually  hit the pretty print at the end to  tidy up
the XML layout eliminate gratuitous CFetc   Is this causing issues?   It
isnt really viable not to?

**Comment by Aurige** [comment]
Yes, the pretty print is most likely the issue (you can also tune it in preferences)
You can check your commits with Github Desktop: then you easily see if they focus on what you added, or if they come with a lot of additional unwanted changes.

**Comment by ue71603** [comment]
@skinkie  can this one be closed?

**Comment by ue71603** [comment]
integrated into  #612

**Pull request closed without merging**
