### PR TITLE
Rename all xsd files (and references to them) to not contain version

### PR DESCRIPTION
**Pull request by csolem**
See #13

Change was done using two bash one-liners:
```
find . -iname "*.xsd" | while read file; do newName=$(echo $file | sed 's/-v1\.[0-9]//g');  if [ "$file" != "$newName" ]; then echo "$file -> $newName"; mv $file $newName; fi; done;
```

```
find . -iname "*.xsd" | while read file; do sed -i 's/-v1\.[0-9]//g' $file; done;
```

Changes have been confirmed to work with xmllint and a valid netex xml file:
```
 xmllint --noout --schema xsd/NeTEx_publication.xsd some_netex_file.xml
```

Verification of compatibility with other currently unmerged pull requests:
I have tested that it is possible to merge this code into the branch containing #9

### CODE REVIEW

**Comment by skinkie** [comment]
I would love to merge this directly... but I guess @nick-knowles  which has 1.09 will be very angry. Hence I would like to see his pull request to see how this conflicts.

**Comment by csolem** [comment]
Ok. Where is the ongoing work for 1.09 located, @nick-knowles ? Is this a separate fork of this NeTEx-CEN repository? Maybe I could help to verify that this change is something that could easily be merged?

**Comment by csolem** [comment]
Another way of publishing to github until permissions are fixed:
Only solution I can think of is to:
- Fork this repository to your https://github.com/nick-knowles (Seems like you already have this fork)
- Create a branch from this (netex-cen) repository's master in your fork. (Requires git remote to be configured to both local and NeTEx-CEN repository)
 `git checkout NeTEx-CEN/master -b newbranch`
- Finally, push and create a pull request from that branch.

**Comment by skinkie** [comment]
Why the revert?

**Comment by csolem** [comment]
I reverted because after other changes it's easier to do it again.
Question: Should the siri version suffix be dropped as well?

**Comment by skinkie** [comment]
I wonder what the upstream SIRI XSD looks like. We might want to update that 'in place' or better: have it actually as submodule in this project.

**Comment by csolem** [comment]
Updated with:
`find . -iname "*.xsd" | grep -v siri | while read file; do newName=$(echo $file | sed 's/-v[0-9]\.[0-9]//g');  if [ "$file" != "$newName" ]; then echo "$file -> $newName"; mv $file $newName; fi; done;`


and using intellij with:
`(?<!(siri_)(utility|location|request_errorConditions|requests|types|participant|base|common_services|request_support|requests_errorConditions))-v[0-9].[0-9]\.xsd`

Validation of examples gives the same amount of issues as the master branch.

**Comment by csolem** [comment]
The PR is read for review and merging

**Pull request merged**
