### PR TITLE
Start the initial NeTEx repository with clean XML and XSD files, including travis-ci validation

### PR DESCRIPTION
**Pull request by skinkie**

### CODE REVIEW

**Comment by Aurige** [comment]
I did a quick walk through and that's mostly look Ok (didn't find any real issue). Just a few comments:

- We need to keep the XMLSpy and Oxygen project files (.spp and .xpr files) already used by a lot of users
- I'm in favour of keeping the Reame.txt file which is convenient for people not using Github (so they have an easy to read file telling them where they are in the NeTEx update process)
- The Readme.md need to be updated 

@nick-knowles is it Ok for you ?

**Comment by Aurige** [comment]
Great !

**Comment by nick-knowles** [comment]
Christophe is right - 
a) We need the OXYGEN and XML Spy files -they are crucial for  supporting tools for efficient editing. 

b) We need the readme.txt for several reasons. One of the  most important as it acts as a checklist to  makes sure the documentation  and the UML model is also updated to reflected changes to  the XML (Which is usually a bigger task than just  changing the schema...) and vice versa.   If multiple people are making changes to the schema, then this is even more important to keep  track of. 

c) It is also valuable 
I suggest we implement a process such that the high level entry is made in the readme.me file every time a group of changes are uploaded in. It should be annotated with whether it is an xsd only change, or whether the uml and or specification needs to be updated. When the uml/ documentation has been changed, the entry should be updated with the version number of the NeTEx EA  & Netex doc that contains the change 
For examl

 * FIX: Reorganise   project folders   [*xsd only*]
   * Split all_object_part3_fares into four sublists -FP, FS, AR, SD

 * CR: CR0030	Add **DayOffsets** [*uml:TODO; doc:TODO*]
   * netex_coupledJourney_version-v1.1.xsd UM p
   * netex_datedPassingTime_version-v1.1.xsd  
   * netex_monitoredPassingTime_version-v1.1.xsd  
   * netex_passingTimes_version-v1.1.xsd  

Once documentation has been done

 * CR: CR0030	Add **DayOffsets** [*uml:v96-nk2; doc:v38.03*] 
   * netex_coupledJourney_version-v1.1.xsd UM p
   * netex_datedPassingTime_version-v1.1.xsd  
   * netex_monitoredPassingTime_version-v1.1.xsd  
   * netex_passingTimes_version-v1.1.xsd  

I made a revised version of the readme..md file to show how this might look e (and also to fix some errors in teh draft MD file.  My example includes marked up entries for all the changes since 1.07   
 
However  I dont seem to be authorised to push to the Github Netex project - ANy ideas?
I get a message "Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository."

The file I am trying to upload is 
[README.md.txt](https://github.com/NeTEx-CEN/NeTEx/files/1647699/README.md.txt)

**Comment by syversenkr** [comment]
Have created pull request #4 adding the oXygen and XMLspy project files from neTEx_XML-1.08.zip

**Pull request merged**
