### PR TITLE
Remove redundant sequence

### PR DESCRIPTION
**Pull request by skinkie**
For discussion: #286

### CODE REVIEW

**Comment by ue71603** [comment]
@skinkie  How do we progress?

**Comment by skinkie** [comment]
@ue71603 @Aurige mentioned this needs to be checked for every instance where this happens in EA. I have obviously sent him every instance...

**Review by ue71603 — APPROVED** [review]
There was only one to be found? Then ok

**Comment by skinkie** [comment]
> There was only one to be found? Then ok

No, no, no... hunderds... I'll mail ;-)

**Comment by ue71603** [comment]
@skinkie  @Aurige 
If this should be done:
(1) Say if we do it?
(2) List to be provided here
(3) @trurlurl may start working on it.

**Comment by Aurige** [comment]
It was discussed in one of the meetings, and the decision was to correct this kind of unnecessary sequence when we work on something related (by opportunity): it is too much work (and time) to check all of them one by one, and it does not harm.

**Review by trurlurl — APPROVED** [review]

**Review by Aurige — APPROVED** [review]

**Pull request merged**
