### PR TITLE
Fix version

### PR DESCRIPTION
**Pull request by skinkie**
This attempts to fix the issue #455.

Choices made:
 1. A Version element MUST exist in any file that uses versions.
 2. version="any" cannot be supported unless a Version with version="any" exists.
 3. This likely breaks a lot of examples too, so it is based on the other dataSourceRef branch.

### CODE REVIEW

**Review by ue71603 — APPROVED** [review]

**Comment by skinkie** [comment]
@ue71603 still too many examples that should be fixed first.

**Comment by Aurige** [comment]
see my comments on #455 
Also I don't agree with "_version="any" cannot be supported unless a Version with version="any" exists._" : "any" mean that you can refer to any version you got (having a version number or not). 
But I would agree that an object defined with an id and a version="any" does not really mean anything (but it's harmless)

**Comment by skinkie** [comment]
It is not harmless. Especially because "any" has semantics. A default value specifically stating there is no version would work, since it hopefully wouldn't break constraint checking.

**Comment by ue71603** [comment]
@skinkie  @Aurige  check the last commit. I worked on two examples and this adds layers that I am not sure, if they are good. Also "any" is NOT interpreted as it should. I had to add Datasource with id and version="78" to make it work.

**Comment by Aurige** [comment]
It still looks weird to me (the version of a version, and with Id=version as attribute) it can be a convention, but does not really mean something and can be misunderstood... I personally would really prefer things like `<Version id="78">` for versions. Also defining a version with just an **_Id_** looks like a useless technical artefact to me: the version element was initially created to carry some semantics, not just to hold an Id.
This said, I agree that we need to clarify the semantic of "any"

**Comment by ue71603** [comment]
@skinkie  will update this as we changed stuff already.

**Comment by ue71603** [comment]
@skinkie  should I fix it before you start working? or will you do it anyhow?

**Pull request closed without merging**
