### PR TITLE
Single Files Validation issues (Master)

### PR DESCRIPTION
**Pull request by Aurige**
A few SXD files were not valid when used individually (netex_ifopt_equipmentAccess_support.xsd and netex_ifopt_equipmentSigns_support.xsd for example) This was solved by simply move PlaceEquipmentRef, PlaceEquipmentRefStructure and PlaceEquipmentIdType from netex_equipment_version.xsd to netex_equipment_support.xsd (which is quite logical)

Note: replaces https://github.com/NeTEx-CEN/NeTEx/pull/416/files

### CODE REVIEW

**Review by ue71603 — APPROVED** [review]

**Comment by ue71603** [comment]
....you did it from your own repository and not on the NeTEx-Cen --> CI does not work....

**Comment by Aurige** [comment]
That's something new ... wasn't the initial choice to PR from our own forked repo ?

**Comment by ue71603** [comment]
@skinkie  you might tell Christophe, what the problem is.

**Comment by Aurige** [comment]
From what I can find, we need to create a personal access token with repository access and add this personal token as a github actions secret ... and then make use of it in the Github action ! Unless we decide of another process

**Comment by skinkie** [comment]
Github actions is already active (no secrets required), but I haven't had the time to set it up in next yet.

**Comment by Aurige** [comment]
replace by https://github.com/NeTEx-CEN/NeTEx/pull/431

**Pull request closed without merging**
