### PR TITLE
Fix vehicle equipment profile and ActualEquipmentProfile

### PR DESCRIPTION
**Pull request by nick-knowles**
Allow  multiple members  - Fixe needed for DEck plan change

### CODE REVIEW

**Comment by skinkie** [comment]
Nope.

**Comment by Aurige** [comment]
Better when targeting next
@skinkie : what is the best way to go in such situation where you have several commits in a raw, each one depending in the previous one ... this results in "non atomic" changes since the last PR collects commits (but need them all to be consistent).

**Comment by skinkie** [comment]
I guess: push earlier?

**Comment by Aurige** [comment]
yes, but not always possible/meaningful ... this seems to be a Github limitation to support dependent/stacked pull requests (https://stackoverflow.com/questions/26619478/are-dependent-pull-requests-in-github-possible )
In the case where we have one commit per PR, the easy way is probably to just focus on the latest commit

**Comment by ue71603** [comment]
@trurlurl @skinkie  Also pls here, advise @trurlurl if changes are needed.

**Comment by ue71603** [comment]
done in #615

**Pull request closed without merging**
