### PR TITLE
Allow multiple PrivateCodes under every element.

### LINKED ISSUE #394: PrivateCode under every Object

### LINKED ISSUE #395: Multiple PrivateCode codes under every element

### PR DESCRIPTION
**Pull request by skinkie**
Fix #394
Fix #395

### CODE REVIEW

**Comment by Aurige** [comment]
Fine for me. We should probably put all the "deprecated" comments in the same PR.

**Comment by Aurige** [comment]
Add Type+Value uniqueness

**Comment by Aurige** [comment]
What can we do with this PR (and associated conflicts) ? Recreate it at the end of the revision process ?

**Comment by skinkie** [comment]
I think recreate it, is fine for me.

**Comment by skinkie** [comment]
Replaced by #544

**Comment by trurlurl** [comment]
Removing "documentation update needed" since closed without merging.

**Pull request closed without merging**
